# Numpy Project - Part 2: The Validity of a solution

We'll reveal the true objective of this project: create an algorithm to solve sudokus! That'll be a ton of fun, but for now, we need to first nail down a few required functions.

For this second part, we'll be trying to validate a board; if a proposed solution is valid or not. As you might know, the rules of Sudoku are straightforward: there are numbers 1-9 and they can't be repeated in either rows, columns or 3x3 blocks.

**IMPORTANT:** This 2nd part will use the `Board` class produced in Part 1. Make sure all the tests are passing.

In [1]:
import numpy as np
import collections

from sudoku import Board

In this case, we'll use the following two sudoku boards. Our original one from part 1:

<img src="https://user-images.githubusercontent.com/872296/68136001-49d21400-ff03-11e9-8750-acb846e23046.png" width="600px">

In [2]:
arr_valid = np.array([
    [0, 2, 0, 0, 8, 0, 0, 5, 0],
    [4, 0, 0, 0, 0, 6, 8, 0, 0],
    [6, 0, 0, 4, 5, 3, 9, 7, 0],
    [0, 0, 0, 0, 0, 2, 0, 9, 0],
    [0, 0, 4, 0, 0, 0, 6, 0, 0],
    [0, 1, 0, 3, 0, 0, 0, 0, 0],
    [0, 5, 7, 1, 3, 4, 0, 0, 9],
    [0, 0, 9, 6, 0, 0, 0, 0, 5],
    [0, 3, 0, 0, 2, 0, 0, 8, 0]])

and an "invalid" one, that we've purposely invalidated to practice these functions. We've introduced 3 numbers that invalidate sudoku rules (marked in red):

<img src="https://user-images.githubusercontent.com/872296/68214887-05a34a00-ffbd-11e9-9f6f-922b69599428.png" width="600px" align="center">

The number `5` added in the 2nd row, 2nd column invalidates the board because there's another number `5` in the same column. The number `8` invalidates as there's another `8` in the same block, and `4` is repeated in the same row.

In [3]:
arr_invalid = np.array([
    [0, 2, 0, 0, 8, 0, 0, 5, 0],
    [4, 5, 0, 0, 8, 6, 8, 0, 0],
    [6, 0, 0, 4, 5, 3, 9, 7, 0],
    [0, 0, 0, 0, 0, 2, 0, 9, 0],
    [0, 0, 4, 0, 0, 0, 6, 4, 0],
    [0, 1, 0, 3, 0, 0, 0, 0, 0],
    [0, 5, 7, 1, 3, 4, 0, 0, 9],
    [0, 0, 9, 6, 0, 0, 0, 0, 5],
    [0, 3, 0, 0, 2, 0, 0, 8, 0]])

Initializing now the boards objects:

In [4]:
valid = Board(arr_valid)
invalid = Board(arr_invalid)

### Testing if a row, column or block is valid

We'll write a function `is_subset_valid` that will receive either a row, column or block, and return if it's valid or not.

##### a) Checking rows

In [5]:
def is_subset_valid(arr):
    clean_arr = arr[arr > 0]
    arr_set = set(clean_arr)
    if len(arr_set) == clean_arr.size:
        return True
    return False

Let's test it with different things:

In [6]:
valid_row = valid.get_row(1)
valid_row

array([4, 0, 0, 0, 0, 6, 8, 0, 0])

In [7]:
assert is_subset_valid(valid_row) is True

In [8]:
invalid_row = invalid.get_row(4)
invalid_row  # Number 4 is repeated

array([0, 0, 4, 0, 0, 0, 6, 4, 0])

In [9]:
assert is_subset_valid(invalid_row) is False

##### a) Checking columns

In [10]:
valid_col = valid.get_column(3)
valid_col

array([0, 0, 4, 0, 0, 3, 1, 6, 0])

In [11]:
assert is_subset_valid(valid_col) is True

In [12]:
invalid_col = invalid.get_column(1)
invalid_col  # Number 5 is repeated

array([2, 5, 0, 0, 0, 1, 5, 0, 3])

In [13]:
assert is_subset_valid(invalid_col) is False

##### a) Checking blocks

In [14]:
valid_block = valid.get_block(0, 1)
valid_block

array([[0, 8, 0],
       [0, 0, 6],
       [4, 5, 3]])

In [15]:
assert is_subset_valid(valid_block) is True

In [16]:
invalid_block = invalid.get_block(0, 1)
invalid_block  # Number 8 is repeated

array([[0, 8, 0],
       [0, 8, 6],
       [4, 5, 3]])

In [17]:
assert is_subset_valid(invalid_block) is False

### Testing a valid board

We can now move forward to our `is_valid` function, that will receive a `Board` and will check if it's valid or not.

In [18]:
def is_valid(board):
    
    tests = list() # Holds all of the True and False values of the tests being run
    
    # Test all rows 
    for row in board.iter_rows():
        tests.append(is_subset_valid(row))
    
    # Test all columns
    for col in board.iter_columns():
        tests.append(is_subset_valid(col))
        
    # Test all Blocks
    for block in board.iter_blocks():
        tests.append(is_subset_valid(block))
        
    # Return True if all values in tests are True, False otherwise
    return all(tests)

And now we can test it:

In [19]:
assert is_valid(valid) is True

In [20]:
assert is_valid(invalid) is False

## Time to test!

Now it's time to move your code to `sudoku.py` and then run all the tests; if they're passing, you can move to the next step!

In [ ]:
!py.test test_part_2.py